name: C/C++ CI and Maven Package

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: oraclelinux:8
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
      - run: |
          yum install -y epel-release
          yum install -y make gcc-c++ openssl-devel utf8proc-devel
      - run: |
          cd $GITHUB_WORKSPACE/src
          make build
      - uses: actions/upload-artifact@v7
        with:
          name: osptoolkit
          path: |
            ${{ github.workspace }}/lib/libosptk.a
          if-no-files-found: error

  package:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v5
        with:
          java-version: "21"
          distribution: "corretto"
          cache: "maven"
          server-id: github
      - uses: actions/download-artifact@v8
        with:
          name: osptoolkit
      - run: |
          mv libosptk.a lib
          mvn -B install
