name: C/C++ CI and Maven Package

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: oraclelinux:8
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - run: |
          yum install -y epel-release
          yum install -y make gcc-c++ openssl-devel utf8proc-devel
      - run: |
          cd $GITHUB_WORKSPACE/src
          make build
      - uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: osptoolkit
          path: |
            ${{ github.workspace }}/lib/libosptk.a
          if-no-files-found: error

  package:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          java-version: "21"
          distribution: "corretto"
          cache: "maven"
          server-id: github
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: osptoolkit
      - run: |
          mv libosptk.a lib
          mvn -B clean install
