name: C/C++ CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # os: [centos7, rhel8]
        os: [rhel8]
        include:
          # - os: centos7
          #   container: "centos:7"
          - os: rhel8
            container: "oraclelinux:8"
    container: ${{ matrix.container }}

    steps:
      - name: checkout for centos7
        if: ${{ matrix.os == 'centos7' }}
        uses: actions/checkout@v3

      - name: checkout for rhel8
        if: ${{ matrix.os == 'rhel8' }}
        uses: actions/checkout@v4

      - name: install dependencies
        run: |
          yum install -y epel-release
          yum install -y make gcc-c++ openssl-devel utf8proc-devel

      - name: make osptk
        run: |
          cd $GITHUB_WORKSPACE/src
          make build

      - name: make test_app
        run: |
          cd $GITHUB_WORKSPACE/test
          make linux
