name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    container: 'centos:7'
    
    steps:
    - uses: actions/checkout@v4
    - name: install dependencies
      run: |
        yum install -y epel-release
        yum install -y make gcc-c++ openssl-devel utf8proc-devel
    - name: make osptk
      run: |
        cd $GITHUB_WORKSPACE/src
        make build
    - name: make test_app
      run: |
        cd $GITHUB_WORKSPACE/test
        make linux
    
